apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat-service
  namespace: default
  labels:
    app: heartbeat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeat-service
  template:
    metadata:
      labels:
        app: heartbeat-service
    spec:
      containers:
        - name: heartbeat-service
          image: iwinxdigitaltechnologies/heartbeat-service:latest
          imagePullPolicy: Always
          env:
            # NATS Config
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NATS_URL
            - name: NATS_SUBJECT
              value: "attendance.heartbeat"
            - name: STREAM_NAME
              value: "attendance"

            # Redis Config
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_PASSWORD

            # Temporal Config
            - name: TEMPORAL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TEMPORAL_ADDRESS



      restartPolicy: Always
