apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-credentials
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: local-db-secret
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: local-db-secret
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: local-db-secret
        property: password
    - secretKey: DB_PORT
      remoteRef:
        key: local-db-secret
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: local-db-secret
        property: dbname

    - secretKey: REDIS_HOST
      remoteRef:
        key: local-redis-secret
        property: host
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: local-redis-secret
        property: password

    - secretKey: NATS_URL
      remoteRef:
        key: local-nats-secret
        property: url

    - secretKey: S3_DIRECTUS_BUCKET
      remoteRef:
        key: local-s3-secret
        property: directus_bucket
    - secretKey: S3_BACKUP_BUCKET
      remoteRef:
        key: local-s3-secret
        property: backup_bucket
    - secretKey: S3_REGION
      remoteRef:
        key: local-s3-secret
        property: region

    - secretKey: TEMPORAL_ADDRESS
      remoteRef:
        key: local-service-endpoints
        property: temporal_address
    - secretKey: OPENFAAS_URL
      remoteRef:
        key: local-service-endpoints
        property: openfaas_url
