apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: local-secret-store
  namespace: default
spec:
  provider:
    kubernetes:
      namespace: default
      auth:
        serviceAccount:
          name: external-secrets
