apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: senzr-backend-root1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harish-senzr/backend.git
    targetRevision: development
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
