apiVersion: apps/v1
kind: Deployment
metadata:
  name: postrecord-service
  labels:
    app: postrecord-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postrecord-service
  template:
    metadata:
      labels:
        app: postrecord-service
    spec:
      containers:
        - name: postrecord-service
          image: harish7305/postrecord-service:latest
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NATS_URL
            - name: NATS_SUBJECT
              value: "attendance.face"
            - name: STREAM_NAME
              value: "attendance"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_PASSWORD
            - name: TEMPORAL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TEMPORAL_ADDRESS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
      restartPolicy: Always
